export const ActionTypes = {
  BEGIN_SET_PRODUCT_CATEGORIES: "BEGIN_SET_PRODUCT_CATEGORIES",
  SET_PRODUCT_CATEGORIES: "SET_PRODUCTS_CATEGORIE",
  BEGIN_SET_PRODUCTS: "BEGIN_SET_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  BEGIN_SET_CARTS: "BEGIN_SET_CARTS",
  SET_CARTS: "SET_CARTS",
  BEGIN_SELECTED_PRODUCT: "BEGIN_SELECTED_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  BEGIN_UPDATE_SELECTED_PRODUCT: "BEGIN_UPDATE_SELECTED_PRODUCT",
  UPDATE_SELECTED_PRODUCT: "UPDATE_SELECTED_PRODUCT",
  BEGIN_REMOVE_SELECTED_PRODUCT: "BEGIN_REMOVE_SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};